[package]
name = "ca_orbs"
version = "0.1.0"
edition = "2021"
authors = ["Ardu"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
bevy= "0.8.0"
bevy_egui = "0.15"